//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLAIM.Ressources.FormTexts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CLAIM.Ressources.FormTexts.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un montant allant jusqu&apos;à 50% du montant d&apos;assurance, sans dépasser 100 000$ peut être demandé. Si une prestation anticipée a déjà été versée, elle déterminera le montant actuellement disponible..
        /// </summary>
        internal static string Description_AcceleratedAmount {
            get {
                return ResourceManager.GetString("Description_AcceleratedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce formulaire permet de faire une réclamation en ligne pour obtenir une avance sur le versement du montant d’assurance prévu au décès. Prévoyez environ 10 minutes pour le compléter. Un premier suivi vous sera fait au plus tard 5 jours ouvrables après l’envoi de la réclamation..
        /// </summary>
        internal static string Description_AcceleratedForm {
            get {
                return ResourceManager.GetString("Description_AcceleratedForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce formulaire permet de faire une réclamation d’assurance maladie grave en ligne. Prévoyez environ 20  minutes pour le compléter. Un premier suivi sera fait au propriétaire de la police d’assurance au plus tard 5 jours ouvrables après l’envoi de la réclamation..
        /// </summary>
        internal static string Description_CriticalIllnessForm {
            get {
                return ResourceManager.GetString("Description_CriticalIllnessForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un problème de santé.
        /// </summary>
        internal static string Family_AddHealthProblem {
            get {
                return ResourceManager.GetString("Family_AddHealthProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de problème de santé.
        /// </summary>
        internal static string Family_HealthProblemType {
            get {
                return ResourceManager.GetString("Family_HealthProblemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Année.
        /// </summary>
        internal static string Family_HealthProblemYear {
            get {
                return ResourceManager.GetString("Family_HealthProblemYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Père ou mère.
        /// </summary>
        internal static string Family_LabelParent {
            get {
                return ResourceManager.GetString("Family_LabelParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frère ou sœur.
        /// </summary>
        internal static string Family_LabelSibling {
            get {
                return ResourceManager.GetString("Family_LabelSibling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lien de parenté.
        /// </summary>
        internal static string Family_Relationship {
            get {
                return ResourceManager.GetString("Family_Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DadMom.
        /// </summary>
        internal static string Family_ValueParent {
            get {
                return ResourceManager.GetString("Family_ValueParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrotherSister.
        /// </summary>
        internal static string Family_ValueSibling {
            get {
                return ResourceManager.GetString("Family_ValueSibling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos de votre maladie.
        /// </summary>
        internal static string Header_AboutIllness {
            get {
                return ResourceManager.GetString("Header_AboutIllness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos de vous.
        /// </summary>
        internal static string Header_AboutInsured {
            get {
                return ResourceManager.GetString("Header_AboutInsured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        internal static string Header_Address {
            get {
                return ResourceManager.GetString("Header_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant de la prestation de décès anticipée demandé.
        /// </summary>
        internal static string Header_BenefitAmount {
            get {
                return ResourceManager.GetString("Header_BenefitAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À qui devons-nous transmettre la prestation ?.
        /// </summary>
        internal static string Header_BenefitsRecipient {
            get {
                return ResourceManager.GetString("Header_BenefitsRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sommaire.
        /// </summary>
        internal static string Header_Confirmation {
            get {
                return ResourceManager.GetString("Header_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réclamation prestation de décès anticipée - Déclaration du demandeur.
        /// </summary>
        internal static string Header_Confirmation_AcceleratedBenefit {
            get {
                return ResourceManager.GetString("Header_Confirmation_AcceleratedBenefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réclamation maladie grave - Déclaration du demandeur.
        /// </summary>
        internal static string Header_Confirmation_CriticalIllness {
            get {
                return ResourceManager.GetString("Header_Confirmation_CriticalIllness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de naissance.
        /// </summary>
        internal static string Header_DateOfBirth {
            get {
                return ResourceManager.GetString("Header_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déclaration.
        /// </summary>
        internal static string Header_Declaration {
            get {
                return ResourceManager.GetString("Header_Declaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature de la maladie / Diagnostic du médecin.
        /// </summary>
        internal static string Header_DiseaseNature {
            get {
                return ResourceManager.GetString("Header_DiseaseNature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membres de la famille.
        /// </summary>
        internal static string Header_FamilyMembers {
            get {
                return ResourceManager.GetString("Header_FamilyMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un membre de votre famille immédiate (père, mère, frère ou sœur) a-t-il déjà souffert d’un problème de santé similaire?.
        /// </summary>
        internal static string Header_FamilySimilarIllness {
            get {
                return ResourceManager.GetString("Header_FamilySimilarIllness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À quel titre effectuez-vous cette réclamation ?.
        /// </summary>
        internal static string Header_FilingClaimAs {
            get {
                return ResourceManager.GetString("Header_FilingClaimAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effectuez-vous cette demande pour vous-même?.
        /// </summary>
        internal static string Header_FilingForSelf {
            get {
                return ResourceManager.GetString("Header_FilingForSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de la première consultation avec un médecin au sujet de la maladie.
        /// </summary>
        internal static string Header_FirstConsultationDate {
            get {
                return ResourceManager.GetString("Header_FirstConsultationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de l’apparition des premiers symptômes de la maladie.
        /// </summary>
        internal static string Header_FirstSymptomsDate {
            get {
                return ResourceManager.GetString("Header_FirstSymptomsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Décrire tous les symptômes ressentis.
        /// </summary>
        internal static string Header_IllnessSymptoms {
            get {
                return ResourceManager.GetString("Header_IllnessSymptoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous un conseiller en assurance de personnes ?.
        /// </summary>
        internal static string Header_InsuranceAdvisor {
            get {
                return ResourceManager.GetString("Header_InsuranceAdvisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La police d’assurance.
        /// </summary>
        internal static string Header_InsurancePolicy {
            get {
                return ResourceManager.GetString("Header_InsurancePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de police d’assurance  (10 chiffres).
        /// </summary>
        internal static string Header_InsurancePolicyNumber {
            get {
                return ResourceManager.GetString("Header_InsurancePolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic du médecin.
        /// </summary>
        internal static string Header_PhysicianDiagnosis {
            get {
                return ResourceManager.GetString("Header_PhysicianDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Médecin ayant assuré le suivi médical et médecin de famille (s’il y a lieu).
        /// </summary>
        internal static string Header_ProvidingOrFamilyPhysician {
            get {
                return ResourceManager.GetString("Header_ProvidingOrFamilyPhysician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Médecin ayant assuré le suivi médical.
        /// </summary>
        internal static string Header_ProvidingPhysician {
            get {
                return ResourceManager.GetString("Header_ProvidingPhysician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre réclamation.
        /// </summary>
        internal static string Header_YourClaim {
            get {
                return ResourceManager.GetString("Header_YourClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous aurez besoin….
        /// </summary>
        internal static string Header_YouWillNeed {
            get {
                return ResourceManager.GetString("Header_YouWillNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to des informations à propos d’un problème de santé similaire des membres de la famille..
        /// </summary>
        internal static string Info_RequireFamilySimilarProblems {
            get {
                return ResourceManager.GetString("Info_RequireFamilySimilarProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to du numéro de police d’assurance. &lt;strong&gt;Consultez d’abord cette police pour savoir si la maladie diagnostiquée donne droit à une prestation.&lt;/strong&gt;.
        /// </summary>
        internal static string Info_RequireInsurancePolicyNumber {
            get {
                return ResourceManager.GetString("Info_RequireInsurancePolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Un accusé de réception vous sera transmis après l’envoi de la réclamation..
        /// </summary>
        internal static string Note_ClaimAcknowledgement {
            get {
                return ResourceManager.GetString("Note_ClaimAcknowledgement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du.
        /// </summary>
        internal static string Period_From {
            get {
                return ResourceManager.GetString("Period_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to au.
        /// </summary>
        internal static string Period_To {
            get {
                return ResourceManager.GetString("Period_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je suis le propriétaire de la police d’assurance.
        /// </summary>
        internal static string Test_AsInsurancePolicyOwner {
            get {
                return ResourceManager.GetString("Test_AsInsurancePolicyOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un numéro de police d’assurance.
        /// </summary>
        internal static string Text_AddInsurancePolicy {
            get {
                return ResourceManager.GetString("Text_AddInsurancePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Période(s).
        /// </summary>
        internal static string Text_CareDuration {
            get {
                return ResourceManager.GetString("Text_CareDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir....
        /// </summary>
        internal static string Text_Choice {
            get {
                return ResourceManager.GetString("Text_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        internal static string Text_City {
            get {
                return ResourceManager.GetString("Text_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous avons reçu votre réclamation.
        /// </summary>
        internal static string Text_ClaimReception {
            get {
                return ResourceManager.GetString("Text_ClaimReception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous avons reçu la réclamation.
        /// </summary>
        internal static string Text_ClaimReception_DMGPA {
            get {
                return ResourceManager.GetString("Text_ClaimReception_DMGPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raison de la consultation.
        /// </summary>
        internal static string Text_ConsultationReason {
            get {
                return ResourceManager.GetString("Text_ConsultationReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous souhaitez faire la réclamation par téléphone ? Composez le &lt;a href=&quot;tel:{0}&quot;&gt;{0}&lt;/a&gt;..
        /// </summary>
        internal static string Text_ContactUsPhone {
            get {
                return ResourceManager.GetString("Text_ContactUsPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je déclare que les renseignements fournis dans cette réclamation sont exacts et que toute déclaration faite au cours d’un entretien en personne ou par téléphone concernant la présente réclamation sera exacte et complète. Je consens à ce que toutes ces déclarations forment la base de toute prestation approuvée pour cette réclamation..
        /// </summary>
        internal static string Text_Declaration {
            get {
                return ResourceManager.GetString("Text_Declaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Établissement de santé.
        /// </summary>
        internal static string Text_HealthcareFacility {
            get {
                return ResourceManager.GetString("Text_HealthcareFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Au conseiller en assurance de personnes.
        /// </summary>
        internal static string Text_InsuranceAdvisor {
            get {
                return ResourceManager.GetString("Text_InsuranceAdvisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À l&apos;assuré.
        /// </summary>
        internal static string Text_InsurancePolicyInsured {
            get {
                return ResourceManager.GetString("Text_InsurancePolicyInsured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nos numéros de police d’assurance ont 10 chiffres. Si celui de l’assuré a un format différent, communiquez avec le service à la clientèle au &lt;a href=&quot;tel:1 844 442-4636&quot;&gt;1 844 442-4636&lt;/a&gt;..
        /// </summary>
        internal static string Text_InsurancePolicyNumber {
            get {
                return ResourceManager.GetString("Text_InsurancePolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Au propriétaire de la police d’assurance.
        /// </summary>
        internal static string Text_InsurancePolicyOwner {
            get {
                return ResourceManager.GetString("Text_InsurancePolicyOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom de l’assuré.
        /// </summary>
        internal static string Text_InsuredFirstName {
            get {
                return ResourceManager.GetString("Text_InsuredFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;assuré.
        /// </summary>
        internal static string Text_InsuredLastName {
            get {
                return ResourceManager.GetString("Text_InsuredLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si la réclamation concerne plus d’une police d’assurance, inscrivez tous les numéros de police..
        /// </summary>
        internal static string Text_MultipleInsurancePolicies {
            get {
                return ResourceManager.GetString("Text_MultipleInsurancePolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je ne suis pas le propriétaire de la police d’assurance.
        /// </summary>
        internal static string Text_NotAsInsurancePolicyOwner {
            get {
                return ResourceManager.GetString("Text_NotAsInsurancePolicyOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Médecin consulté.
        /// </summary>
        internal static string Text_PhysicianConsulted {
            get {
                return ResourceManager.GetString("Text_PhysicianConsulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indiquez le diagnostic du médecin.
        /// </summary>
        internal static string Text_PhysicianDiagnosis {
            get {
                return ResourceManager.GetString("Text_PhysicianDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom du nouveau médecin.
        /// </summary>
        internal static string Text_PhysicianFirstName {
            get {
                return ResourceManager.GetString("Text_PhysicianFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string Text_PhysicianLastName {
            get {
                return ResourceManager.GetString("Text_PhysicianLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un numéro de suivi et des informations sur son utilité vous seront transmis par courriel dans quelques minutes. Les prochaines étapes vous seront confirmées au plus tard dans 5 jours ouvrables.&lt;br&gt;&lt;br&gt;Bonne journée,.
        /// </summary>
        internal static string Text_TrackingEmailSent {
            get {
                return ResourceManager.GetString("Text_TrackingEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un numéro de suivi et des indications qui vous permettront de suivre l’évolution de la réclamation en ligne vous seront transmis par courriel dans quelques minutes. Les prochaines étapes vous seront confirmées au plus tard dans 5 jours ouvrables..
        /// </summary>
        internal static string Text_TrackingEmailSent_DECES {
            get {
                return ResourceManager.GetString("Text_TrackingEmailSent_DECES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un numéro de suivi et des indications qui vous permettront de suivre l’évolution de la réclamation en ligne vous seront transmis par courriel dans quelques minutes. Les prochaines étapes vous seront confirmées au plus tard dans 5 jours ouvrables..
        /// </summary>
        internal static string Text_TrackingEmailSent_MGPA {
            get {
                return ResourceManager.GetString("Text_TrackingEmailSent_MGPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre courriel.
        /// </summary>
        internal static string Text_YourEmail {
            get {
                return ResourceManager.GetString("Text_YourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre prénom.
        /// </summary>
        internal static string Text_YourFirstName {
            get {
                return ResourceManager.GetString("Text_YourFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre nom.
        /// </summary>
        internal static string Text_YourLastName {
            get {
                return ResourceManager.GetString("Text_YourLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos de la prestation de décès anticipée.
        /// </summary>
        internal static string Title_AboutBenefit {
            get {
                return ResourceManager.GetString("Title_AboutBenefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faire une réclamation.
        /// </summary>
        internal static string Title_FileClaim {
            get {
                return ResourceManager.GetString("Title_FileClaim", resourceCulture);
            }
        }
    }
}
