//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLAIM.Ressources.FormTexts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CLAIM.Ressources.FormTexts.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de décès doit être plus grande que la date de naissance..
        /// </summary>
        internal static string Date_Deces_Naissance {
            get {
                return ResourceManager.GetString("Date_Deces_Naissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez inscrire une adresse..
        /// </summary>
        internal static string Error_Address {
            get {
                return ResourceManager.GetString("Error_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez faire un choix..
        /// </summary>
        internal static string Error_ChoiceRequired {
            get {
                return ResourceManager.GetString("Error_ChoiceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez inscrire votre prénom..
        /// </summary>
        internal static string Error_FirstName {
            get {
                return ResourceManager.GetString("Error_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce formulaire a déjà été soumis..
        /// </summary>
        internal static string Error_FormSubmitted {
            get {
                return ResourceManager.GetString("Error_FormSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez inscrire un numéro de police d’assurance valide..
        /// </summary>
        internal static string Error_InsurancePolicy {
            get {
                return ResourceManager.GetString("Error_InsurancePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez inscrire le prénom de l’assuré..
        /// </summary>
        internal static string Error_InsuredFirstName {
            get {
                return ResourceManager.GetString("Error_InsuredFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez inscrire le nom de l’assuré..
        /// </summary>
        internal static string Error_InsuredLastName {
            get {
                return ResourceManager.GetString("Error_InsuredLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez saisir un montant valide..
        /// </summary>
        internal static string Error_InvalidAmount {
            get {
                return ResourceManager.GetString("Error_InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez inscrire votre nom..
        /// </summary>
        internal static string Error_LastName {
            get {
                return ResourceManager.GetString("Error_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez inscrire un code postal valide.
        /// </summary>
        internal static string Error_PostalCode {
            get {
                return ResourceManager.GetString("Error_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date doit être plus petite ou égale à la date du jour..
        /// </summary>
        internal static string Future_Date {
            get {
                return ResourceManager.GetString("Future_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de fin doit être plus grande ou égale à la date de début..
        /// </summary>
        internal static string Incompatible_Dates {
            get {
                return ResourceManager.GetString("Incompatible_Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez saisir un montant de prestation anticipée valide..
        /// </summary>
        internal static string Invalid_BenefitAmount {
            get {
                return ResourceManager.GetString("Invalid_BenefitAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez indiquer une date valide..
        /// </summary>
        internal static string Invalid_DateFormat {
            get {
                return ResourceManager.GetString("Invalid_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez inscrire un courriel valide..
        /// </summary>
        internal static string Invalid_Email {
            get {
                return ResourceManager.GetString("Invalid_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez inscrire un numéro de téléphone valide..
        /// </summary>
        internal static string Invalid_PhoneNumber {
            get {
                return ResourceManager.GetString("Invalid_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez inscrire la ville..
        /// </summary>
        internal static string Missing_City {
            get {
                return ResourceManager.GetString("Missing_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez cocher la case &quot;Je déclare...&quot;..
        /// </summary>
        internal static string Missing_Confirmation {
            get {
                return ResourceManager.GetString("Missing_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez inscrire la raison.
        /// </summary>
        internal static string Missing_ConsultationReason {
            get {
                return ResourceManager.GetString("Missing_ConsultationReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez inscrire l’année de consultation.
        /// </summary>
        internal static string Missing_ConsultationYear {
            get {
                return ResourceManager.GetString("Missing_ConsultationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez inscrire le diagnostic du médecin..
        /// </summary>
        internal static string Missing_Diagnosis {
            get {
                return ResourceManager.GetString("Missing_Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez inscrire le lien de parenté..
        /// </summary>
        internal static string Missing_FamilyRelationship {
            get {
                return ResourceManager.GetString("Missing_FamilyRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez indiquer une date de première consultation..
        /// </summary>
        internal static string Missing_FirstConsultationDate {
            get {
                return ResourceManager.GetString("Missing_FirstConsultationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez inscrire le nom de l’établissement où vous avez été traité..
        /// </summary>
        internal static string Missing_HealthcareFacility {
            get {
                return ResourceManager.GetString("Missing_HealthcareFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez inscrire un type de problème de santé..
        /// </summary>
        internal static string Missing_HealthProblemType {
            get {
                return ResourceManager.GetString("Missing_HealthProblemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez inscrire l’année du problème de santé..
        /// </summary>
        internal static string Missing_HealthProblemYear {
            get {
                return ResourceManager.GetString("Missing_HealthProblemYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez décrire les symptômes ressentis..
        /// </summary>
        internal static string Missing_IllnessSymptoms {
            get {
                return ResourceManager.GetString("Missing_IllnessSymptoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez inscrire le prénom du médecin..
        /// </summary>
        internal static string Missing_PhysicianFirstName {
            get {
                return ResourceManager.GetString("Missing_PhysicianFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez inscrire le nom du médecin..
        /// </summary>
        internal static string Missing_PhysicianLastName {
            get {
                return ResourceManager.GetString("Missing_PhysicianLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez inscrire la spécialité du médecin..
        /// </summary>
        internal static string Missing_PhysicianSpecialty {
            get {
                return ResourceManager.GetString("Missing_PhysicianSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez inscrire la province..
        /// </summary>
        internal static string Missing_Province {
            get {
                return ResourceManager.GetString("Missing_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date doit être plus grande ou égale à la date du jour..
        /// </summary>
        internal static string Past_Date {
            get {
                return ResourceManager.GetString("Past_Date", resourceCulture);
            }
        }
    }
}
