//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLAIM.Ressources.FormTexts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UI_Representative {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI_Representative() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CLAIM.Ressources.FormTexts.UI_Representative", typeof(UI_Representative).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos de la maladie de {0}.
        /// </summary>
        internal static string Header_AboutIllness {
            get {
                return ResourceManager.GetString("Header_AboutIllness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos de {0}.
        /// </summary>
        internal static string Header_AboutInsured {
            get {
                return ResourceManager.GetString("Header_AboutInsured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un membre de la famille immédiate de l’assuré (père, mère, frère ou sœur) a-t-il déjà souffert d’un problème de santé similaire?.
        /// </summary>
        internal static string Header_FamilySimilarIllness {
            get {
                return ResourceManager.GetString("Header_FamilySimilarIllness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Médecin ayant assuré le suivi médical et médecin de famille (s’il y a lieu).
        /// </summary>
        internal static string Header_ProvidingOrFamilyPhysician {
            get {
                return ResourceManager.GetString("Header_ProvidingOrFamilyPhysician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un numéro de suivi et des informations sur son utilité vous seront transmis par courriel dans quelques minutes. Les prochaines étapes vous seront confirmées au plus tard dans 5 jours ouvrables.&lt;br&gt;&lt;br&gt;Bonne journée,.
        /// </summary>
        internal static string Text_TrackingEmailSent {
            get {
                return ResourceManager.GetString("Text_TrackingEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un numéro de suivi et des indications qui vous permettront de suivre l’évolution de la réclamation en ligne vous seront transmis par courriel dans quelques minutes. Les prochaines étapes vous seront confirmées au plus tard dans 5 jours ouvrables..
        /// </summary>
        internal static string Text_TrackingEmailSent_MGPA {
            get {
                return ResourceManager.GetString("Text_TrackingEmailSent_MGPA", resourceCulture);
            }
        }
    }
}
