//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLAIM.Ressources.FormTexts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIAddress {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIAddress() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CLAIM.Ressources.FormTexts.UIAddress", typeof(UIAddress).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex. 1-304 rue Joliette, Québec, QC.
        /// </summary>
        internal static string AddressExample {
            get {
                return ResourceManager.GetString("AddressExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App./Bur..
        /// </summary>
        internal static string ApartmentField {
            get {
                return ResourceManager.GetString("ApartmentField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        internal static string CityField {
            get {
                return ResourceManager.GetString("CityField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB.
        /// </summary>
        internal static string CodeProvinceAlberta {
            get {
                return ResourceManager.GetString("CodeProvinceAlberta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC.
        /// </summary>
        internal static string CodeProvinceColombieBritannique {
            get {
                return ResourceManager.GetString("CodeProvinceColombieBritannique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPE.
        /// </summary>
        internal static string CodeProvinceIlePrinceEdouard {
            get {
                return ResourceManager.GetString("CodeProvinceIlePrinceEdouard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string CodeProvinceManitoba {
            get {
                return ResourceManager.GetString("CodeProvinceManitoba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NB.
        /// </summary>
        internal static string CodeProvinceNouveauBrunswick {
            get {
                return ResourceManager.GetString("CodeProvinceNouveauBrunswick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NS.
        /// </summary>
        internal static string CodeProvinceNouvelleEcosse {
            get {
                return ResourceManager.GetString("CodeProvinceNouvelleEcosse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NU.
        /// </summary>
        internal static string CodeProvinceNunavut {
            get {
                return ResourceManager.GetString("CodeProvinceNunavut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string CodeProvinceOntario {
            get {
                return ResourceManager.GetString("CodeProvinceOntario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC.
        /// </summary>
        internal static string CodeProvinceQuebec {
            get {
                return ResourceManager.GetString("CodeProvinceQuebec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SK.
        /// </summary>
        internal static string CodeProvinceSaskatchewan {
            get {
                return ResourceManager.GetString("CodeProvinceSaskatchewan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NL.
        /// </summary>
        internal static string CodeProvinceTerreNeuve {
            get {
                return ResourceManager.GetString("CodeProvinceTerreNeuve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT.
        /// </summary>
        internal static string CodeProvinceTerritoiresNO {
            get {
                return ResourceManager.GetString("CodeProvinceTerritoiresNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YT.
        /// </summary>
        internal static string CodeProvinceYukon {
            get {
                return ResourceManager.GetString("CodeProvinceYukon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer ici pour saisir une adresse au Canada.
        /// </summary>
        internal static string InCanada {
            get {
                return ResourceManager.GetString("InCanada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone principal.
        /// </summary>
        internal static string MainPhone {
            get {
                return ResourceManager.GetString("MainPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alberta.
        /// </summary>
        internal static string NomProvinceAlberta {
            get {
                return ResourceManager.GetString("NomProvinceAlberta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombie-Britannique.
        /// </summary>
        internal static string NomProvinceColombieBritannique {
            get {
                return ResourceManager.GetString("NomProvinceColombieBritannique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Île-du-Prince-Édouard.
        /// </summary>
        internal static string NomProvinceIlePrinceEdouard {
            get {
                return ResourceManager.GetString("NomProvinceIlePrinceEdouard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manitoba.
        /// </summary>
        internal static string NomProvinceManitoba {
            get {
                return ResourceManager.GetString("NomProvinceManitoba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau-Brunswick.
        /// </summary>
        internal static string NomProvinceNouveauBrunswick {
            get {
                return ResourceManager.GetString("NomProvinceNouveauBrunswick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle-Écosse.
        /// </summary>
        internal static string NomProvinceNouvelleEcosse {
            get {
                return ResourceManager.GetString("NomProvinceNouvelleEcosse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nunavut.
        /// </summary>
        internal static string NomProvinceNunavut {
            get {
                return ResourceManager.GetString("NomProvinceNunavut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontario.
        /// </summary>
        internal static string NomProvinceOntario {
            get {
                return ResourceManager.GetString("NomProvinceOntario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Québec.
        /// </summary>
        internal static string NomProvinceQuebec {
            get {
                return ResourceManager.GetString("NomProvinceQuebec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saskatchewan.
        /// </summary>
        internal static string NomProvinceSaskatchewan {
            get {
                return ResourceManager.GetString("NomProvinceSaskatchewan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terre-Neuve-et-Labrador.
        /// </summary>
        internal static string NomProvinceTerreNeuve {
            get {
                return ResourceManager.GetString("NomProvinceTerreNeuve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territoires du Nord-Ouest.
        /// </summary>
        internal static string NomProvinceTerritoiresNO {
            get {
                return ResourceManager.GetString("NomProvinceTerritoiresNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yukon.
        /// </summary>
        internal static string NomProvinceYukon {
            get {
                return ResourceManager.GetString("NomProvinceYukon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro.
        /// </summary>
        internal static string NumberField {
            get {
                return ResourceManager.GetString("NumberField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer ici pour saisir une adresse hors Canada.
        /// </summary>
        internal static string OutsideCanada {
            get {
                return ResourceManager.GetString("OutsideCanada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poste.
        /// </summary>
        internal static string PhoneExtension {
            get {
                return ResourceManager.GetString("PhoneExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CP.
        /// </summary>
        internal static string POBoxPrint {
            get {
                return ResourceManager.GetString("POBoxPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case postale.
        /// </summary>
        internal static string PostalBoxField {
            get {
                return ResourceManager.GetString("PostalBoxField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case postale ou route rurale.
        /// </summary>
        internal static string PostalBoxSection {
            get {
                return ResourceManager.GetString("PostalBoxSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code postal.
        /// </summary>
        internal static string PostalCodeField {
            get {
                return ResourceManager.GetString("PostalCodeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string ProvinceField {
            get {
                return ResourceManager.GetString("ProvinceField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route rurale.
        /// </summary>
        internal static string RuralRouteField {
            get {
                return ResourceManager.GetString("RuralRouteField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisir l’adresse ou le code postal.
        /// </summary>
        internal static string SearchField {
            get {
                return ResourceManager.GetString("SearchField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone secondaire.
        /// </summary>
        internal static string SecondaryPhone {
            get {
                return ResourceManager.GetString("SecondaryPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succursale.
        /// </summary>
        internal static string StationField {
            get {
                return ResourceManager.GetString("StationField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCC.
        /// </summary>
        internal static string StationPrint {
            get {
                return ResourceManager.GetString("StationPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rue.
        /// </summary>
        internal static string StreetField {
            get {
                return ResourceManager.GetString("StreetField", resourceCulture);
            }
        }
    }
}
