//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLAIM.Ressources.FormTexts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIUnsolicited {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIUnsolicited() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CLAIM.Ressources.FormTexts.UIUnsolicited", typeof(UIUnsolicited).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations ou commentaires.
        /// </summary>
        internal static string AutreInfos {
            get {
                return ResourceManager.GetString("AutreInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum de 5000 caractères.
        /// </summary>
        internal static string AutreInfosMax {
            get {
                return ResourceManager.GetString("AutreInfosMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to caractères.
        /// </summary>
        internal static string Caracteres {
            get {
                return ResourceManager.GetString("Caracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... de la date d&apos;une chirurgie.
        /// </summary>
        internal static string Chirurgie {
            get {
                return ResourceManager.GetString("Chirurgie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’information sera ajoutée au dossier afin que le responsable de l’étude de la réclamation en prenne connaissance. Au besoin, un suivi sera effectué. Bonne journée,.
        /// </summary>
        internal static string ConfirmationMessage {
            get {
                return ResourceManager.GetString("ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous avons reçu l’information!.
        /// </summary>
        internal static string ConfirmationTitle {
            get {
                return ResourceManager.GetString("ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... de la date d&apos;une consultation avec une médecin spécialiste.
        /// </summary>
        internal static string Consultation {
            get {
                return ResourceManager.GetString("Consultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez préciser l’information..
        /// </summary>
        internal static string Er03 {
            get {
                return ResourceManager.GetString("Er03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Établissement de santé.
        /// </summary>
        internal static string Etablissement {
            get {
                return ResourceManager.GetString("Etablissement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joindre un document.
        /// </summary>
        internal static string JoindreDocument {
            get {
                return ResourceManager.GetString("JoindreDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Médecin spécialiste.
        /// </summary>
        internal static string MedecinSpecialiste {
            get {
                return ResourceManager.GetString("MedecinSpecialiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string NomMedecin {
            get {
                return ResourceManager.GetString("NomMedecin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        internal static string PrenomMedecin {
            get {
                return ResourceManager.GetString("PrenomMedecin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... d&apos;une date de retour au travail.
        /// </summary>
        internal static string RetourAuTravail {
            get {
                return ResourceManager.GetString("RetourAuTravail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spécialité du médecin.
        /// </summary>
        internal static string Specialite {
            get {
                return ResourceManager.GetString("Specialite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je souhaite vous informer....
        /// </summary>
        internal static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information supplémentaire.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de chirurgie.
        /// </summary>
        internal static string TypeChirurgie {
            get {
                return ResourceManager.GetString("TypeChirurgie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        internal static string Ville {
            get {
                return ResourceManager.GetString("Ville", resourceCulture);
            }
        }
    }
}
